### ISSUE TITLE
Missing keys CK62

### ISSUE THREAD

**Issue by pointer2002** [socram/dotfiles#1]
Thanks Marcos 
great job.
**There are missing keys like tilde for ntilde **for example .  
=>  ñ
Don´t know how to produce them easily ... Any clue ?
Maybe a combination of Mode_switch key plus a letter could be fine.
Same thing for accents ... not easy with this keyboard.

**These are my addons to your ck62 great job** 
first : help =>
!# Help [https://wiki.linuxquestions.org/wiki/List_of_Keysyms_Recognised_by_Xmodmap](https://wiki.linuxquestions.org/wiki/List_of_Keysyms_Recognised_by_Xmodmap) 
then i added these keys F11 and F12 (with basic tilde)
keycode  20 = minus underscore F11 underscore
keycode  21 = equal plus F12 asciitilde

Maybe usefull to say the **layer 3** seems to be the most usefull for having default keyboard keys

**Comment by socram** [comment]
Hello, Thank yo for your appreciation,

This is not my work,  I got this config from this dude -> https://gist.github.com/luccamendonca

From this link - > https://gist.github.com/luccamendonca/df48e9a0e0dd5ea8333c5ba4bafd62d3

And yes, i'm from Brazil and i need to use tilde and anothers like ã,é,à,ç

With this tiny keyboard ( CK62 ) i use the following key combinations

to ã = > Shift + Caps + Esc + a ( or n, ñ )
to à => Caps + esc + a

You can try and let me know if it works ?

**Comment by pointer2002** [comment]
Yeah it works. Thanks. 
I bought this keyboard recently and was frustrated not to have accents (I'm French)  thanks to you I can manage to draw accentuated letters even if it's not obvious in Linux. Not tried yet on windows. 
I've seen that there are 3 layers when you press Fn + 3 (or 1 or 2) for 5 seconds and this kb draws a complete différents set of keys.
As I use layer 3 these commands for xmodmap ain't work so I added my own xmodmap redefine keys. 
This work is great and I learn what was a dead_key using that. 
I'll post it in another comment if you want. 
Many thanks.
Johnny
